/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendacomics;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AlumMati
 */
public class Comics extends javax.swing.JFrame {

    static public ResultSet r;
    static public Connection connec;

    public Comics() throws SQLException {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SUPERHEROES COMICS");
        String url = "jdbc:mysql://localhost:3306/bd_aplicacion";
        String user = "root";
        String pass = "";
        connec = DriverManager.getConnection(url, user, pass);

        Statement s = (Statement) connec.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from Comics CO";
        r = s.executeQuery(query);
        r.first();

        Id.setText(r.getString("Identificador"));
        Nombre.setText(r.getString("Nombre"));
        Edicion.setText(r.getString("Edicion"));
        Coleccion.setText(r.getString("Coleccion"));
        Autor.setText(r.getString("Autor"));
        Estado.setText(r.getString("Estado"));
        Distribuidor.setText(r.getString("Distribuidor"));
        Editorial.setText(r.getString("Editorial"));

        Id.setEditable(false);
        Nombre.setEditable(false);
        Edicion.setEditable(false);
        Coleccion.setEditable(false);
        Autor.setEditable(false);
        Estado.setEditable(false);
        Distribuidor.setEditable(false);
        Editorial.setEditable(false);
        Insertar.setEnabled(false);
        Cancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Edicion = new javax.swing.JTextField();
        Autor = new javax.swing.JTextField();
        Coleccion = new javax.swing.JTextField();
        Estado = new javax.swing.JTextField();
        Distribuidor = new javax.swing.JTextField();
        Editorial = new javax.swing.JTextField();
        Anterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        Ultimo = new javax.swing.JButton();
        Primero = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comics");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edición");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Colección");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Autor");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Distribuidor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Editorial");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 231, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 231, -1));

        Edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdicionActionPerformed(evt);
            }
        });
        getContentPane().add(Edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 231, -1));

        Autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorActionPerformed(evt);
            }
        });
        getContentPane().add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 231, -1));

        Coleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColeccionActionPerformed(evt);
            }
        });
        getContentPane().add(Coleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 231, -1));

        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 231, -1));

        Distribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistribuidorActionPerformed(evt);
            }
        });
        getContentPane().add(Distribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 231, -1));

        Editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorialActionPerformed(evt);
            }
        });
        getContentPane().add(Editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 231, -1));

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        Ultimo.setText("Último");
        Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoActionPerformed(evt);
            }
        });
        getContentPane().add(Ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 70, -1));

        Primero.setText("Primero");
        Primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(Primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 80, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        getContentPane().add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendacomics/imagenes/captainamerica.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void EdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdicionActionPerformed

    private void AutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorActionPerformed

    private void ColeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColeccionActionPerformed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void DistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistribuidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistribuidorActionPerformed

    private void EditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditorialActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        try {
            if (r.previous()) {
                Id.setText(r.getString("Identificador"));
                Nombre.setText(r.getString("Nombre"));
                Edicion.setText(r.getString("Edicion"));
                Coleccion.setText(r.getString("Coleccion"));
                Autor.setText(r.getString("Autor"));
                Estado.setText(r.getString("Estado"));
                Distribuidor.setText(r.getString("Distribuidor"));
                Editorial.setText(r.getString("Editorial"));
            } else {
                JOptionPane.showMessageDialog(null, "Estás en el primer registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Comics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        try {
            if (r.next()) {
                Id.setText(r.getString("Identificador"));
                Nombre.setText(r.getString("Nombre"));
                Edicion.setText(r.getString("Edicion"));
                Coleccion.setText(r.getString("Coleccion"));
                Autor.setText(r.getString("Autor"));
                Estado.setText(r.getString("Estado"));
                Distribuidor.setText(r.getString("Distribuidor"));
                Editorial.setText(r.getString("Editorial"));
            } else {
                JOptionPane.showMessageDialog(null, "Estás en el último registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Comics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    private void UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoActionPerformed
        try {
            if (r.last()) {
                Id.setText(r.getString("Identificador"));
                Nombre.setText(r.getString("Nombre"));
                Edicion.setText(r.getString("Edicion"));
                Coleccion.setText(r.getString("Coleccion"));
                Autor.setText(r.getString("Autor"));
                Estado.setText(r.getString("Estado"));
                Distribuidor.setText(r.getString("Distribuidor"));
                Editorial.setText(r.getString("Editorial"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Comics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UltimoActionPerformed

    private void PrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeroActionPerformed
        try {
            if (r.first()) {
                Id.setText(r.getString("Identificador"));
                Nombre.setText(r.getString("Nombre"));
                Edicion.setText(r.getString("Edicion"));
                Coleccion.setText(r.getString("Coleccion"));
                Autor.setText(r.getString("Autor"));
                Estado.setText(r.getString("Estado"));
                Distribuidor.setText(r.getString("Distribuidor"));
                Editorial.setText(r.getString("Editorial"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Comics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrimeroActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        try {
            String vId, vNombre, vEdicion, vColeccion, vAutor, vEstado, vDistribuidor, vEditorial;
            vId = Id.getText();
            vNombre = Nombre.getText();
            vEdicion = Edicion.getText();
            vColeccion = Coleccion.getText();
            vAutor = Autor.getText();
            vEstado = Estado.getText();
            vDistribuidor = Distribuidor.getText();
            vEditorial = Editorial.getText();
            String url = "jdbc:mysql://localhost:3306/bd_aplicacion";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            if (Id.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "No has insertado un Identificador");
            } else {
                String query = "insert into Comics values ('" + vId + "','" + vNombre + "','" + vEdicion + "','" + vColeccion + "','" + vAutor + "','" + vEstado + "','" + vDistribuidor + "','" + vEditorial + "')";
                int resultado = s.executeUpdate(query);
                String query2 = "select * from Comics";
                r = s.executeQuery(query2);
                r.first();
            }

            Anterior.setEnabled(true);
            Nuevo.setEnabled(true);
            Siguiente.setEnabled(true);
            Primero.setEnabled(true);
            Ultimo.setEnabled(true);
            Insertar.setEnabled(false);
            Cancelar.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Comics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InsertarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        try {
            Insertar.setEnabled(false);
            Cancelar.setEnabled(false);
            Primero.setEnabled(true);
            Ultimo.setEnabled(true);
            Anterior.setEnabled(true);
            Siguiente.setEnabled(true);
            Volver.setEnabled(true);
            Id.setEditable(false);
            Nombre.setEditable(false);
            Edicion.setEditable(false);
            Coleccion.setEditable(false);
            Autor.setEditable(false);
            Estado.setEditable(false);
            Distribuidor.setEditable(false);
            Editorial.setEditable(false);
            Nuevo.setEnabled(true);

            if (r.first()) {
                Id.setText(r.getString("Identificador"));
                Nombre.setText(r.getString("Nombre"));
                Edicion.setText(r.getString("Edicion"));
                Coleccion.setText(r.getString("Coleccion"));
                Autor.setText(r.getString("Autor"));
                Estado.setText(r.getString("Estado"));
                Distribuidor.setText(r.getString("Distribuidor"));
                Editorial.setText(r.getString("Editorial"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Comics.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_CancelarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        JOptionPane.showMessageDialog(null, "Vas a registrar un nuevo Comic. Pulsa Aceptar para continuar.");

        Id.setEditable(true);
        Nombre.setEditable(true);
        Edicion.setEditable(true);
        Coleccion.setEditable(true);
        Autor.setEditable(true);
        Estado.setEditable(true);
        Distribuidor.setEditable(true);
        Editorial.setEditable(true);
        Anterior.setEnabled(false);
        Nuevo.setEnabled(false);
        Siguiente.setEnabled(false);
        Primero.setEnabled(false);
        Ultimo.setEnabled(false);
        Insertar.setVisible(true);
        Cancelar.setVisible(true);
        Insertar.setEnabled(true);
        Cancelar.setEnabled(true);
        Id.setText(null);
        Nombre.setText(null);
        Edicion.setText(null);
        Coleccion.setText(null);
        Autor.setText(null);
        Estado.setText(null);
        Distribuidor.setText(null);
        Editorial.setText(null);
    }//GEN-LAST:event_NuevoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JTextField Autor;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Coleccion;
    private javax.swing.JTextField Distribuidor;
    private javax.swing.JTextField Edicion;
    private javax.swing.JTextField Editorial;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Id;
    private javax.swing.JButton Insertar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Nuevo;
    private javax.swing.JButton Primero;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Ultimo;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
