/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendacomics;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author AlumMati
 */
public class Historial extends javax.swing.JFrame {

    static public ResultSet r;
    static public Connection connec;

    /**
     * Creates new form Historial
     */
    public Historial() throws SQLException {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("SUPERHEROES COMICS");
        String url = "jdbc:mysql://localhost:3306/bd_aplicacion";
        String user = "root";
        String pass = "";
        connec = DriverManager.getConnection(url, user, pass);

        Statement s = (Statement) connec.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from Historial H";
        r = s.executeQuery(query);
        r.first();

        Id.setText(r.getString("Identificador"));
        IdFac.setText(r.getString("IdFactura"));
        Cliente.setText(r.getString("Cliente"));
        Precio.setText(r.getString("Precio"));

        Id.setEditable(false);
        IdFac.setEditable(false);
        Cliente.setEditable(false);
        Precio.setEditable(false);
        Insertar.setEnabled(false);
        Cancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        IdFac = new javax.swing.JTextField();
        Cliente = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Cancelar = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        Ultimo = new javax.swing.JButton();
        Primero = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IdFactura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 218, -1));
        getContentPane().add(IdFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 218, -1));
        getContentPane().add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 218, -1));
        getContentPane().add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 218, -1));

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        getContentPane().add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        Ultimo.setText("Último");
        Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoActionPerformed(evt);
            }
        });
        getContentPane().add(Ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, -1));

        Primero.setText("Primero");
        Primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeroActionPerformed(evt);
            }
        });
        getContentPane().add(Primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, -1));

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        getContentPane().add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendacomics/imagenes/venom.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        try {
            if (r.previous()) {
                Id.setText(r.getString("Identificador"));
                IdFac.setText(r.getString("IdFactura"));
                Cliente.setText(r.getString("Cliente"));
                Precio.setText(r.getString("Precio"));

            } else {
                JOptionPane.showMessageDialog(null, "Estás en el primer registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        try {
            if (r.next()) {
                Id.setText(r.getString("Identificador"));
                IdFac.setText(r.getString("IdFactura"));
                Cliente.setText(r.getString("Cliente"));
                Precio.setText(r.getString("Precio"));

            } else {
                JOptionPane.showMessageDialog(null, "Estás en el primer registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    private void UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoActionPerformed
        try {
            if (r.last()) {
                Id.setText(r.getString("Identificador"));
                IdFac.setText(r.getString("IdFactura"));
                Cliente.setText(r.getString("Cliente"));
                Precio.setText(r.getString("Precio"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UltimoActionPerformed

    private void PrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeroActionPerformed
        try {
            if (r.first()) {
                Id.setText(r.getString("Identificador"));
                IdFac.setText(r.getString("IdFactura"));
                Cliente.setText(r.getString("Cliente"));
                Precio.setText(r.getString("Precio"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrimeroActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        try {
            String vId, vIdFac, vCliente, vPrecio;
            vId = Id.getText();
            vIdFac = IdFac.getText();
            vCliente = Cliente.getText();
            vPrecio = Precio.getText();
            String url = "jdbc:mysql://localhost:3306/bd_aplicacion";
            String user = "root";
            String pass = "";
            Connection connection = DriverManager.getConnection(url, user, pass);
            Statement s = connection.createStatement();
            if (Id.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "No has insertado un identificador");
            } else {
                String query = "insert into Historial values ('" + vId + "','" + vIdFac + "','" + vCliente + "','" + vPrecio + "')";
                int resultado = s.executeUpdate(query);
                String query2 = "select * from Historial";
                r = s.executeQuery(query2);
                r.first();
            }
            Anterior.setEnabled(true);
            Nuevo.setEnabled(true);
            Siguiente.setEnabled(true);
            Primero.setEnabled(true);
            Ultimo.setEnabled(true);
            Insertar.setEnabled(false);
            Cancelar.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_InsertarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        try {
            Insertar.setEnabled(false);
            Cancelar.setEnabled(false);
            Primero.setEnabled(true);
            Ultimo.setEnabled(true);
            Anterior.setEnabled(true);
            Siguiente.setEnabled(true);
            Volver.setEnabled(true);
            Id.setEditable(false);
            IdFac.setEditable(false);
            Cliente.setEditable(false);
            Precio.setEditable(false);
            Nuevo.setEnabled(true);

            if (r.first()) {
                Id.setText(r.getString("Identificador"));
                IdFac.setText(r.getString("IdFactura"));
                Cliente.setText(r.getString("Cliente"));
                Precio.setText(r.getString("Precio"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CancelarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        JOptionPane.showMessageDialog(null, "Vas a registrar un nuevo Historial. Pulsa Aceptar para continuar.");

        Id.setEditable(true);
        IdFac.setEditable(true);
        Cliente.setEditable(true);
        Precio.setEditable(true);
        Anterior.setEnabled(false);
        Nuevo.setEnabled(false);
        Siguiente.setEnabled(false);
        Primero.setEnabled(false);
        Ultimo.setEnabled(false);
        Insertar.setVisible(true);
        Cancelar.setVisible(true);
        Insertar.setEnabled(true);
        Cancelar.setEnabled(true);
        Id.setText(null);
        IdFac.setText(null);
        Cliente.setText(null);
        Precio.setText(null);
    }//GEN-LAST:event_NuevoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Cliente;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField IdFac;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField Precio;
    private javax.swing.JButton Primero;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Ultimo;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
